use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlatformConfig {
    pub id: String,
    pub name: String,
    pub color: String,
    pub icon: String,
    pub login_methods: Vec<LoginMethodConfig>,
    pub commands: PlatformCommandsConfig,
    pub features: PlatformFeaturesConfig,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LoginMethodConfig {
    pub method_type: String,
    pub command: String,
    pub extra_fields: Vec<ExtraFieldConfig>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExtraFieldConfig {
    pub key: String,
    pub label: String,
    pub placeholder: String,
    pub field_type: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PlatformCommandsConfig {
    pub check_session: String,
    pub logout: String,
    pub list: String,
    pub refresh: String,
    pub download: String,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub cancel: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub search: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub curriculum: Option<String>,
}

#[derive(Debug, Default, Clone, Serialize, Deserialize)]
pub struct PlatformFeaturesConfig {
    #[serde(skip_serializing_if = "Option::is_none")]
    pub captcha_event: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub has_search: Option<bool>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub download_arg_name: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub list_returns_key: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub item_subtitle_field: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub session_display: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    pub string_ids: Option<bool>,
}

fn creds_method(cmd: &str) -> LoginMethodConfig {
    LoginMethodConfig {
        method_type: "credentials".to_string(),
        command: cmd.to_string(),
        extra_fields: vec![
            ExtraFieldConfig {
                key: "email".to_string(),
                label: "Email".to_string(),
                placeholder: "user@example.com".to_string(),
                field_type: "text".to_string(),
            },
            ExtraFieldConfig {
                key: "password".to_string(),
                label: "Password".to_string(),
                placeholder: "••••••••".to_string(),
                field_type: "password".to_string(),
            },
        ],
    }
}

fn token_method(cmd: &str) -> LoginMethodConfig {
    LoginMethodConfig {
        method_type: "token".to_string(),
        command: cmd.to_string(),
        extra_fields: vec![
            ExtraFieldConfig {
                key: "token".to_string(),
                label: "Bearer Token".to_string(),
                placeholder: "eyJhbGciOi...".to_string(),
                field_type: "text".to_string(),
            },
        ],
    }
}

fn cookies_method(cmd: &str) -> LoginMethodConfig {
    LoginMethodConfig {
        method_type: "cookies".to_string(),
        command: cmd.to_string(),
        extra_fields: vec![
            ExtraFieldConfig {
                key: "cookies".to_string(),
                label: "Cookies".to_string(),
                placeholder: "Paste cookies or JSON...".to_string(),
                field_type: "textarea".to_string(),
            },
        ],
    }
}

pub fn all_platforms() -> Vec<PlatformConfig> {
    vec![
        PlatformConfig {
            id: "hotmart".to_string(),
            name: "Hotmart".to_string(),
            color: "#F04E23".to_string(),
            icon: "hotmart".to_string(),
            login_methods: vec![creds_method("hotmart_login"), token_method("hotmart_login_token")],
            commands: PlatformCommandsConfig {
                check_session: "hotmart_check_session".to_string(),
                logout: "hotmart_logout".to_string(),
                list: "hotmart_list_courses".to_string(),
                refresh: "hotmart_refresh_courses".to_string(),
                download: "start_course_download".to_string(),
                cancel: Some("cancel_course_download".to_string()),
                search: None,
                curriculum: None,
            },
            features: PlatformFeaturesConfig {
                item_subtitle_field: Some("price".to_string()),
                ..Default::default()
            },
        },
        PlatformConfig {
            id: "udemy".to_string(),
            name: "Udemy".to_string(),
            color: "#A435F0".to_string(),
            icon: "udemy".to_string(),
            login_methods: vec![cookies_method("udemy_login_cookies")],
            commands: PlatformCommandsConfig {
                check_session: "udemy_check_session".to_string(),
                logout: "udemy_logout".to_string(),
                list: "udemy_list_courses".to_string(),
                refresh: "udemy_refresh_courses".to_string(),
                download: "start_udemy_course_download".to_string(),
                cancel: Some("cancel_udemy_course_download".to_string()),
                search: None,
                curriculum: None,
            },
            features: PlatformFeaturesConfig {
                item_subtitle_field: Some("num_published_lectures".to_string()),
                ..Default::default()
            },
        },
        PlatformConfig {
            id: "kiwify".to_string(),
            name: "Kiwify".to_string(),
            color: "#22C55E".to_string(),
            icon: "kiwify".to_string(),
            login_methods: vec![creds_method("kiwify_login"), token_method("kiwify_login_token")],
            commands: PlatformCommandsConfig {
                check_session: "kiwify_check_session".to_string(),
                logout: "kiwify_logout".to_string(),
                list: "kiwify_list_courses".to_string(),
                refresh: "kiwify_refresh_courses".to_string(),
                download: "start_kiwify_course_download".to_string(),
                cancel: None,
                search: None,
                curriculum: None,
            },
            features: Default::default(),
        },
        PlatformConfig {
            id: "skool".to_string(),
            name: "Skool".to_string(),
            color: "#F59E0B".to_string(),
            icon: "skool".to_string(),
            login_methods: vec![creds_method("skool_login"), token_method("skool_login_token")],
            commands: PlatformCommandsConfig {
                check_session: "skool_check_session".to_string(),
                logout: "skool_logout".to_string(),
                list: "skool_list_groups".to_string(),
                refresh: "skool_refresh_groups".to_string(),
                download: "start_skool_course_download".to_string(),
                cancel: None,
                search: None,
                curriculum: None,
            },
            features: Default::default(),
        },
        PlatformConfig {
            id: "gumroad".to_string(),
            name: "Gumroad".to_string(),
            color: "#FF90E8".to_string(),
            icon: "gumroad".to_string(),
            login_methods: vec![creds_method("gumroad_login"), token_method("gumroad_login_token")],
            commands: PlatformCommandsConfig {
                check_session: "gumroad_check_session".to_string(),
                logout: "gumroad_logout".to_string(),
                list: "gumroad_list_products".to_string(),
                refresh: "gumroad_refresh_products".to_string(),
                download: "start_gumroad_download".to_string(),
                cancel: None,
                search: None,
                curriculum: None,
            },
            features: Default::default(),
        },
        PlatformConfig {
            id: "rocketseat".to_string(),
            name: "Rocketseat".to_string(),
            color: "#8257E5".to_string(),
            icon: "rocketseat".to_string(),
            login_methods: vec![token_method("rocketseat_login_token")],
            commands: PlatformCommandsConfig {
                check_session: "rocketseat_check_session".to_string(),
                logout: "rocketseat_logout".to_string(),
                list: "rocketseat_list_courses".to_string(),
                refresh: "rocketseat_refresh_courses".to_string(),
                download: "start_rocketseat_course_download".to_string(),
                cancel: None,
                search: Some("rocketseat_search_courses".to_string()),
                curriculum: None,
            },
            features: Default::default(),
        },
        PlatformConfig {
            id: "teachable".to_string(),
            name: "Teachable".to_string(),
            color: "#00B4B4".to_string(),
            icon: "teachable".to_string(),
            login_methods: vec![token_method("teachable_login_token")],
            commands: PlatformCommandsConfig {
                check_session: "teachable_check_session".to_string(),
                logout: "teachable_logout".to_string(),
                list: "teachable_list_courses".to_string(),
                refresh: "teachable_refresh_courses".to_string(),
                download: "start_teachable_course_download".to_string(),
                cancel: None,
                search: None,
                curriculum: None,
            },
            features: Default::default(),
        },
        PlatformConfig {
            id: "kajabi".to_string(),
            name: "Kajabi".to_string(),
            color: "#0069FF".to_string(),
            icon: "kajabi".to_string(),
            login_methods: vec![token_method("kajabi_login_token")],
            commands: PlatformCommandsConfig {
                check_session: "kajabi_check_session".to_string(),
                logout: "kajabi_logout".to_string(),
                list: "kajabi_list_courses".to_string(),
                refresh: "kajabi_refresh_courses".to_string(),
                download: "start_kajabi_course_download".to_string(),
                cancel: None,
                search: None,
                curriculum: None,
            },
            features: Default::default(),
        },
        PlatformConfig {
            id: "thinkific".to_string(),
            name: "Thinkific".to_string(),
            color: "#1E3A8A".to_string(),
            icon: "thinkific".to_string(),
            login_methods: vec![creds_method("thinkific_login")],
            commands: PlatformCommandsConfig {
                check_session: "thinkific_check_session".to_string(),
                logout: "thinkific_logout".to_string(),
                list: "thinkific_list_courses".to_string(),
                refresh: "thinkific_refresh_courses".to_string(),
                download: "start_thinkific_course_download".to_string(),
                cancel: None,
                search: None,
                curriculum: None,
            },
            features: Default::default(),
        },
        PlatformConfig {
            id: "pluralsight".to_string(),
            name: "Pluralsight".to_string(),
            color: "#F15B2A".to_string(),
            icon: "pluralsight".to_string(),
            login_methods: vec![cookies_method("pluralsight_login_cookies")],
            commands: PlatformCommandsConfig {
                check_session: "pluralsight_check_session".to_string(),
                logout: "pluralsight_logout".to_string(),
                list: "pluralsight_list_courses".to_string(),
                refresh: "pluralsight_refresh_courses".to_string(),
                download: "start_pluralsight_course_download".to_string(),
                cancel: None,
                search: None,
                curriculum: None,
            },
            features: Default::default(),
        },
        PlatformConfig {
            id: "greatcourses".to_string(),
            name: "The Great Courses (Wondrium)".to_string(),
            color: "#0072CE".to_string(),
            icon: "greatcourses".to_string(),
            login_methods: vec![creds_method("wondrium_login"), token_method("wondrium_login_token")],
            commands: PlatformCommandsConfig {
                check_session: "wondrium_check_session".to_string(),
                logout: "wondrium_logout".to_string(),
                list: "wondrium_list_courses".to_string(),
                refresh: "wondrium_refresh_courses".to_string(),
                download: "start_wondrium_course_download".to_string(),
                cancel: None,
                search: None,
                curriculum: None,
            },
            features: Default::default(),
        },
        PlatformConfig {
            id: "masterclass".to_string(),
            name: "MasterClass".to_string(),
            color: "#D4AF37".to_string(),
            icon: "masterclass".to_string(),
            login_methods: vec![cookies_method("masterclass_login_cookies")],
            commands: PlatformCommandsConfig {
                check_session: "masterclass_check_session".to_string(),
                logout: "masterclass_logout".to_string(),
                list: "masterclass_list_courses".to_string(),
                refresh: "masterclass_refresh_courses".to_string(),
                download: "start_masterclass_course_download".to_string(),
                cancel: None,
                search: None,
                curriculum: None,
            },
            features: Default::default(),
        },
        PlatformConfig {
            id: "greenn".to_string(),
            name: "Greenn Club".to_string(),
            color: "#00C853".to_string(),
            icon: "greenn".to_string(),
            login_methods: vec![token_method("greenn_login_token")],
            commands: PlatformCommandsConfig {
                check_session: "greenn_check_session".to_string(),
                logout: "greenn_logout".to_string(),
                list: "greenn_list_courses".to_string(),
                refresh: "greenn_refresh_courses".to_string(),
                download: "start_greenn_course_download".to_string(),
                cancel: None,
                search: None,
                curriculum: None,
            },
            features: Default::default(),
        },
        PlatformConfig {
            id: "kirvano".to_string(),
            name: "Kirvano".to_string(),
            color: "#6366F1".to_string(),
            icon: "kirvano".to_string(),
            login_methods: vec![creds_method("kirvano_login"), token_method("kirvano_login_token")],
            commands: PlatformCommandsConfig {
                check_session: "kirvano_check_session".to_string(),
                logout: "kirvano_logout".to_string(),
                list: "kirvano_list_courses".to_string(),
                refresh: "kirvano_refresh_courses".to_string(),
                download: "start_kirvano_course_download".to_string(),
                cancel: None,
                search: None,
                curriculum: None,
            },
            features: Default::default(),
        },
        PlatformConfig {
            id: "cademi".to_string(),
            name: "Cademi".to_string(),
            color: "#E11D48".to_string(),
            icon: "cademi".to_string(),
            login_methods: vec![creds_method("cademi_login")],
            commands: PlatformCommandsConfig {
                check_session: "cademi_check_session".to_string(),
                logout: "cademi_logout".to_string(),
                list: "cademi_list_courses".to_string(),
                refresh: "cademi_refresh_courses".to_string(),
                download: "start_cademi_course_download".to_string(),
                cancel: None,
                search: None,
                curriculum: None,
            },
            features: Default::default(),
        },
        PlatformConfig {
            id: "memberkit".to_string(),
            name: "MemberKit".to_string(),
            color: "#3B82F6".to_string(),
            icon: "memberkit".to_string(),
            login_methods: vec![creds_method("memberkit_login")],
            commands: PlatformCommandsConfig {
                check_session: "memberkit_check_session".to_string(),
                logout: "memberkit_logout".to_string(),
                list: "memberkit_list_courses".to_string(),
                refresh: "memberkit_refresh_courses".to_string(),
                download: "start_memberkit_course_download".to_string(),
                cancel: None,
                search: None,
                curriculum: None,
            },
            features: Default::default(),
        },
        PlatformConfig {
            id: "cakto".to_string(),
            name: "Cakto".to_string(),
            color: "#8B5CF6".to_string(),
            icon: "cakto".to_string(),
            login_methods: vec![creds_method("cakto_login"), token_method("cakto_login_token")],
            commands: PlatformCommandsConfig {
                check_session: "cakto_check_session".to_string(),
                logout: "cakto_logout".to_string(),
                list: "cakto_list_courses".to_string(),
                refresh: "cakto_refresh_courses".to_string(),
                download: "start_cakto_course_download".to_string(),
                cancel: None,
                search: None,
                curriculum: None,
            },
            features: Default::default(),
        },
        PlatformConfig {
            id: "caktomembers".to_string(),
            name: "Cakto Members".to_string(),
            color: "#7C3AED".to_string(),
            icon: "caktomembers".to_string(),
            login_methods: vec![token_method("caktomembers_login_token")],
            commands: PlatformCommandsConfig {
                check_session: "caktomembers_check_session".to_string(),
                logout: "caktomembers_logout".to_string(),
                list: "caktomembers_list_courses".to_string(),
                refresh: "caktomembers_refresh_courses".to_string(),
                download: "start_caktomembers_course_download".to_string(),
                cancel: None,
                search: None,
                curriculum: None,
            },
            features: Default::default(),
        },
        PlatformConfig {
            id: "curseduca".to_string(),
            name: "Curseduca".to_string(),
            color: "#06B6D4".to_string(),
            icon: "curseduca".to_string(),
            login_methods: vec![creds_method("curseduca_login"), token_method("curseduca_login_token")],
            commands: PlatformCommandsConfig {
                check_session: "curseduca_check_session".to_string(),
                logout: "curseduca_logout".to_string(),
                list: "curseduca_list_courses".to_string(),
                refresh: "curseduca_refresh_courses".to_string(),
                download: "start_curseduca_course_download".to_string(),
                cancel: None,
                search: None,
                curriculum: None,
            },
            features: Default::default(),
        },
        PlatformConfig {
            id: "dsa".to_string(),
            name: "Data Science Academy".to_string(),
            color: "#0284C7".to_string(),
            icon: "dsa".to_string(),
            login_methods: vec![token_method("dsa_login_token")],
            commands: PlatformCommandsConfig {
                check_session: "dsa_check_session".to_string(),
                logout: "dsa_logout".to_string(),
                list: "dsa_list_courses".to_string(),
                refresh: "dsa_refresh_courses".to_string(),
                download: "start_dsa_course_download".to_string(),
                cancel: None,
                search: None,
                curriculum: None,
            },
            features: Default::default(),
        },
        PlatformConfig {
            id: "entregadigital".to_string(),
            name: "Entrega Digital".to_string(),
            color: "#10B981".to_string(),
            icon: "entregadigital".to_string(),
            login_methods: vec![token_method("entregadigital_login_token")],
            commands: PlatformCommandsConfig {
                check_session: "entregadigital_check_session".to_string(),
                logout: "entregadigital_logout".to_string(),
                list: "entregadigital_list_courses".to_string(),
                refresh: "entregadigital_refresh_courses".to_string(),
                download: "start_entregadigital_course_download".to_string(),
                cancel: None,
                search: None,
                curriculum: None,
            },
            features: Default::default(),
        },
        PlatformConfig {
            id: "estrategia_concursos".to_string(),
            name: "Estratégia Concursos".to_string(),
            color: "#0284C7".to_string(),
            icon: "estrategia_concursos".to_string(),
            login_methods: vec![token_method("estrategia_concursos_login_token")],
            commands: PlatformCommandsConfig {
                check_session: "estrategia_concursos_check_session".to_string(),
                logout: "estrategia_concursos_logout".to_string(),
                list: "estrategia_concursos_list_courses".to_string(),
                refresh: "estrategia_concursos_refresh_courses".to_string(),
                download: "start_estrategia_concursos_course_download".to_string(),
                cancel: None,
                search: None,
                curriculum: None,
            },
            features: Default::default(),
        },
        PlatformConfig {
            id: "estrategia_ldi".to_string(),
            name: "Estratégia LDI".to_string(),
            color: "#0369A1".to_string(),
            icon: "estrategia_ldi".to_string(),
            login_methods: vec![token_method("estrategia_ldi_login_token")],
            commands: PlatformCommandsConfig {
                check_session: "estrategia_ldi_check_session".to_string(),
                logout: "estrategia_ldi_logout".to_string(),
                list: "estrategia_ldi_list_courses".to_string(),
                refresh: "estrategia_ldi_refresh_courses".to_string(),
                download: "start_estrategia_ldi_course_download".to_string(),
                cancel: None,
                search: None,
                curriculum: None,
            },
            features: Default::default(),
        },
        PlatformConfig {
            id: "estrategia_militares".to_string(),
            name: "Estratégia Militares".to_string(),
            color: "#0F766E".to_string(),
            icon: "estrategia_militares".to_string(),
            login_methods: vec![token_method("estrategia_militares_login_token")],
            commands: PlatformCommandsConfig {
                check_session: "estrategia_militares_check_session".to_string(),
                logout: "estrategia_militares_logout".to_string(),
                list: "estrategia_militares_list_courses".to_string(),
                refresh: "estrategia_militares_refresh_courses".to_string(),
                download: "start_estrategia_militares_course_download".to_string(),
                cancel: None,
                search: Some("estrategia_militares_search_courses".to_string()),
                curriculum: None,
            },
            features: Default::default(),
        },
        PlatformConfig {
            id: "fluencyacademy".to_string(),
            name: "Fluency Academy".to_string(),
            color: "#EC4899".to_string(),
            icon: "fluencyacademy".to_string(),
            login_methods: vec![creds_method("fluency_login"), token_method("fluency_login_token")],
            commands: PlatformCommandsConfig {
                check_session: "fluency_check_session".to_string(),
                logout: "fluency_logout".to_string(),
                list: "fluency_list_courses".to_string(),
                refresh: "fluency_refresh_courses".to_string(),
                download: "start_fluency_course_download".to_string(),
                cancel: None,
                search: None,
                curriculum: None,
            },
            features: Default::default(),
        },
        PlatformConfig {
            id: "grancursos".to_string(),
            name: "Gran Cursos Online".to_string(),
            color: "#EF4444".to_string(),
            icon: "grancursos".to_string(),
            login_methods: vec![cookies_method("grancursos_login_cookies")],
            commands: PlatformCommandsConfig {
                check_session: "grancursos_check_session".to_string(),
                logout: "grancursos_logout".to_string(),
                list: "grancursos_list_courses".to_string(),
                refresh: "grancursos_refresh_courses".to_string(),
                download: "start_grancursos_course_download".to_string(),
                cancel: None,
                search: None,
                curriculum: None,
            },
            features: Default::default(),
        },
        PlatformConfig {
            id: "medcel".to_string(),
            name: "Medcel".to_string(),
            color: "#059669".to_string(),
            icon: "medcel".to_string(),
            login_methods: vec![creds_method("medcel_login"), token_method("medcel_login_token")],
            commands: PlatformCommandsConfig {
                check_session: "medcel_check_session".to_string(),
                logout: "medcel_logout".to_string(),
                list: "medcel_list_courses".to_string(),
                refresh: "medcel_refresh_courses".to_string(),
                download: "start_medcel_course_download".to_string(),
                cancel: None,
                search: None,
                curriculum: None,
            },
            features: Default::default(),
        },
        PlatformConfig {
            id: "medcof".to_string(),
            name: "Grupo MedCof".to_string(),
            color: "#047857".to_string(),
            icon: "medcof".to_string(),
            login_methods: vec![token_method("medcof_login_token")],
            commands: PlatformCommandsConfig {
                check_session: "medcof_check_session".to_string(),
                logout: "medcof_logout".to_string(),
                list: "medcof_list_courses".to_string(),
                refresh: "medcof_refresh_courses".to_string(),
                download: "start_medcof_course_download".to_string(),
                cancel: None,
                search: None,
                curriculum: None,
            },
            features: Default::default(),
        },
        PlatformConfig {
            id: "medway".to_string(),
            name: "Medway".to_string(),
            color: "#0D9488".to_string(),
            icon: "medway".to_string(),
            login_methods: vec![token_method("medway_login_token")],
            commands: PlatformCommandsConfig {
                check_session: "medway_check_session".to_string(),
                logout: "medway_logout".to_string(),
                list: "medway_list_courses".to_string(),
                refresh: "medway_refresh_courses".to_string(),
                download: "start_medway_course_download".to_string(),
                cancel: None,
                search: None,
                curriculum: None,
            },
            features: Default::default(),
        },
        PlatformConfig {
            id: "nutror".to_string(),
            name: "Eduzz Nutror".to_string(),
            color: "#F97316".to_string(),
            icon: "nutror".to_string(),
            login_methods: vec![token_method("nutror_login_token")],
            commands: PlatformCommandsConfig {
                check_session: "nutror_check_session".to_string(),
                logout: "nutror_logout".to_string(),
                list: "nutror_list_courses".to_string(),
                refresh: "nutror_refresh_courses".to_string(),
                download: "start_nutror_course_download".to_string(),
                cancel: None,
                search: None,
                curriculum: None,
            },
            features: Default::default(),
        },
        PlatformConfig {
            id: "themembers".to_string(),
            name: "The Members".to_string(),
            color: "#6B7280".to_string(),
            icon: "themembers".to_string(),
            login_methods: vec![creds_method("themembers_login"), token_method("themembers_login_token")],
            commands: PlatformCommandsConfig {
                check_session: "themembers_check_session".to_string(),
                logout: "themembers_logout".to_string(),
                list: "themembers_list_courses".to_string(),
                refresh: "themembers_refresh_courses".to_string(),
                download: "start_themembers_course_download".to_string(),
                cancel: None,
                search: None,
                curriculum: None,
            },
            features: Default::default(),
        },
        PlatformConfig {
            id: "voomp".to_string(),
            name: "Voomp Play".to_string(),
            color: "#84CC16".to_string(),
            icon: "voomp".to_string(),
            login_methods: vec![token_method("voomp_login_token")],
            commands: PlatformCommandsConfig {
                check_session: "voomp_check_session".to_string(),
                logout: "voomp_logout".to_string(),
                list: "voomp_list_courses".to_string(),
                refresh: "voomp_refresh_courses".to_string(),
                download: "start_voomp_course_download".to_string(),
                cancel: None,
                search: None,
                curriculum: None,
            },
            features: Default::default(),
        },
        PlatformConfig {
            id: "afya".to_string(),
            name: "Afya Educacional".to_string(),
            color: "#14B8A6".to_string(),
            icon: "afya".to_string(),
            login_methods: vec![creds_method("afya_login"), token_method("afya_login_token")],
            commands: PlatformCommandsConfig {
                check_session: "afya_check_session".to_string(),
                logout: "afya_logout".to_string(),
                list: "afya_list_courses".to_string(),
                refresh: "afya_refresh_courses".to_string(),
                download: "start_afya_course_download".to_string(),
                cancel: None,
                search: None,
                curriculum: None,
            },
            features: Default::default(),
        },
        PlatformConfig {
            id: "alpaclass".to_string(),
            name: "Alpaclass".to_string(),
            color: "#A855F7".to_string(),
            icon: "alpaclass".to_string(),
            login_methods: vec![token_method("alpaclass_login")],
            commands: PlatformCommandsConfig {
                check_session: "alpaclass_check_session".to_string(),
                logout: "alpaclass_logout".to_string(),
                list: "alpaclass_list_courses".to_string(),
                refresh: "alpaclass_refresh_courses".to_string(),
                download: "start_alpaclass_course_download".to_string(),
                cancel: None,
                search: None,
                curriculum: None,
            },
            features: Default::default(),
        },
        PlatformConfig {
            id: "areademembros".to_string(),
            name: "Área de Membros".to_string(),
            color: "#64748B".to_string(),
            icon: "areademembros".to_string(),
            login_methods: vec![token_method("areademembros_login_token")],
            commands: PlatformCommandsConfig {
                check_session: "areademembros_check_session".to_string(),
                logout: "areademembros_logout".to_string(),
                list: "areademembros_list_courses".to_string(),
                refresh: "areademembros_refresh_courses".to_string(),
                download: "start_areademembros_course_download".to_string(),
                cancel: None,
                search: None,
                curriculum: None,
            },
            features: Default::default(),
        },
        PlatformConfig {
            id: "astronmembers".to_string(),
            name: "Astron Members".to_string(),
            color: "#4F46E5".to_string(),
            icon: "astronmembers".to_string(),
            login_methods: vec![creds_method("astron_login"), token_method("astron_login_token")],
            commands: PlatformCommandsConfig {
                check_session: "astron_check_session".to_string(),
                logout: "astron_logout".to_string(),
                list: "astron_list_courses".to_string(),
                refresh: "astron_refresh_courses".to_string(),
                download: "start_astron_course_download".to_string(),
                cancel: None,
                search: None,
                curriculum: None,
            },
            features: Default::default(),
        },
    ]
}

pub fn get_platform_config(id: &str) -> Option<PlatformConfig> {
    all_platforms().into_iter().find(|p| p.id == id)
}
